apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print ( include "fullname" . ) "-postgis-data"| quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.postgis.size }}
