apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print ( include "fullname" . ) "-processed-images"| quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.processed-images.size }}