{{- if eq .Values.postgis.deploy true -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}-secret
data:
  POSTGRES_PASSWORD: {{ .Values.postgis.password | default (randAlphaNum 16) | b64enc }}
  POSTGRES_USER: {{ .Values.postgis.user | default (printf "%s" (include "fullname" .)) | b64enc }}
{{- end -}}
