apiVersion: v1
data:
  POSTGRES_PASSWORD: {{ .Values.postgis.password | default (randAlphaNum 16) | b64enc }}
  POSTGRES_USER: {{ .Values.postgis.user | default (printf "%s" (include "fullname" .)) | b64enc }}
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}-secret
type: Opaque
