apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.3.6.61","10.3.6.63","10.3.6.65"],"port":80,"protocol":"HTTP","serviceName":"openatlas:openatlas","ingressName":"openatlas:openatlas","hostname":"openatlas.acdh-cluster-2.arz.oeaw.ac.at","path":"/","allNodes":false}]
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/8xUX2/iOBD/LiPdW4CkBCh5621pu9LuFgHdezitVoM9Ib51bMue0KIq3/3kACmVVqd7uJP2CTwez8zvz+QV0Kmv5IOyBgpA58Jon0ECP5SRUMAtOW0PNRmGBGpilMgIxSugMZaRlTUhHu32LxIciIde2aFAZk1DZUcqFpnjNisncj6YT67yQb4t88H1LMVBmpGYTeY0n1AKbQIat6T/sVyFoYICiMZjlJRTmk+vp1c0pzTPZuU8m+X5dEbbtMzHguYSEni2/oe2KIdNIH9R6RwPpEmw9SfwQ9kDHlhHBlljePsXpzRYExTwFjuGgkPxPt4mEByJiMd5u/MUwi2h1MrQmoQ1MkAxTdMEPDmtBAYosnjYq6jGgwps/eGTqhVDkaUJvI36CjWyqD71fP3XKOPo7JFpd4jlvdVamd2Tk8h0bP+ybvwu4r2a/BatgS9PBveoNG71OdwmwAcXT6t3BWKcaqfPxS5sJTx1ptqomgJj7aAwjdaX3vg/sJ5kwrJURnHE3CYgrGFUhnyA4s9XILPvfk/6Lx/Xm/vVYv394XG9gQT2qJsYdzZw1BrapM99/LpY/bH6uFl8v73Z3Px+s15cPNisnhbQfktigztv666JsKZUu8/oVlTGyU6F+uIJWBd5Qg1FiTpQG9sFEp743z/5loCqsZNxVwkfWUQhq4ElfB71FI16IgYuupOei6tpluE0h9P7ZaP10molDlDAx/KL5aWncPxoaLUnQyEsvd12cpeodONpU3kKldUSinECFbO7J+52BTnu+AgScNYzFNfpdXS/qKgD9LDZLKOFHHllZb9J3YY0QlAIF6WzBFjVZBt+S/z5Dsde4cz9Ee7yov3pRZwzJnvLVlgd5fuw7NTzhFL9ckA9Bdt4QeFo6cDouXG/1IhMvlam2/rPFEK006mrpP3o4nag7Q5+mn+23p3S1IkhTeiDH3QTmPyd8iH60VNHQn99o5/xEA0QQclGk/9ylFpSiY3mQR+POSQar/jwwRqmFz6SejHQvUdBy/dkjNO2bdu/AwAA//9PqP4RaQcAAA
    objectset.rio.cattle.io/id: 9ab1f5d9-9524-4bf4-870a-01ec759e95e0
  labels:
    objectset.rio.cattle.io/hash: ee33ade4e046862e9e0417f9174467eb0f43ce9d
    workload.user.cattle.io/workloadselector: apps.deployment-openatlas-openatlas
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-openatlas-openatlas
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-openatlas-openatlas
    spec:
      affinity: {}
      containers:
        - env:
            - name: POSTGRES_HOST
              value: postgres
            - name: OVERWRITE_DATABASE
              value: 'TRUE'
          envFrom:
            - configMapRef:
                name: postgres
                optional: false
            - secretRef:
                name: postgres
                optional: false
          image: 'ghcr.io/acdh-oeaw/openatlas/container-preview:2611a64'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: openatlas
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
