apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}
spec:
  rules:
    - host: {{ .Values.hostName | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "fullname" . }}-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
