apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["openatlas/openatlas"]'
    management.cattle.io/ui-managed: 'true'
  name: {{ template "fullname" . }}
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: openatlas
      uid: 7b5aa742-15bb-452d-b32b-002c2e2a4902
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  clusterIP: 10.43.154.161
  clusterIPs:
    - 10.43.154.161
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-openatlas-openatlas
  sessionAffinity: None
  type: ClusterIP
