name:
  daily security update

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 4 * * *"

jobs:
  check_for_updates:
    runs-on: ubuntu-latest
    steps:
      - name: check OpenAtlas container
        run: |
          check_result="$(docker run --rm -u 0:0 --entrypoint /bin/bash ghcr.io/acdh-oeaw/openatlas/container-preview:${{ github.ref_name }} \
            -c 'apt-get update >/dev/null; if [ $(apt list --upgradable 2>/dev/null | wc -l) != 1 ]; then echo -n need to upgrade; else echo -n everything fine ; fi')"
          echo "$check_result"
          echo "check_result=$check_result" >> $GITHUB_OUTPUT
  call_delploy:
    needs: [check_for_updates]
    if: "!  needs.check_for_updates.outputs.check_result == 'need to upgrade'"
    runs-on: ubuntu-latest
    steps:
      - name: check OpenAtlas container
        run: |
          echo "juhu"

   # uses: ./.github/workflows/starter.yaml
   # secrets: inherit
