name: 'OpenAtlas Github Tests'
on:
  push: {}
jobs:
  build_openatlas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tags based on git data
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/container-preview
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{sha}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./install
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test_openatlas:
    runs-on: ubuntu-latest
    needs: [build_openatlas]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create openatlas network
        run: |
          docker network create --internal openatlas

      - name: Create postgis container
        run: |
          docker run --rm -d -e POSTGRES_PASSWORD=verysecret -e POSTGRES_DB=openatlas_test -e POSTGRES_USER=openatlas --name postgres --network openatlas postgis/postgis:13-3.3

      - name: Wait
        run: sleep 8

      - name: Create openatlas container
        run: |
          docker run --rm -d -e POSTGRES_PASSWORD=verysecret -e POSTGRES_DB=openatlas_test -e POSTGRES_USER=openatlas -e POSTGRES_HOST=postgres --name openatlas --network openatlas ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/container-preview:${{ github.ref_name }}

      - name: Execute tests
        run: |
          set -x
          cat <<EOF > testing.py
          DATABASE_NAME='$POSTGRES_DB'
          DATABASE_USER='$POSTGRES_USER'
          DATABASE_HOST='$POSTGRES_HOST'
          DATABASE_PORT=5432
          DATABASE_PASS='$POSTGRES_PASSWORD'
          MAIL_PASSWORD='$MAIL_PASSWORD'
          SECRET_KEY='$COOKIE_KEY'  # Used for cookies
          IS_UNIT_TEST = True
          DEBUG = True
          EOF
          cat <<EOF > production.py
          DATABASE_NAME='$POSTGRES_DB'
          DATABASE_USER='$POSTGRES_USER'
          DATABASE_HOST='$POSTGRES_HOST'
          DATABASE_PORT=5432
          DATABASE_PASS='$POSTGRES_PASSWORD'
          MAIL_PASSWORD='$MAIL_PASSWORD'
          SECRET_KEY='$COOKIE_KEY'  # Used for cookies
          EOF
          cat testing.py
          cat production.py
          docker cp production.py openatlas:/var/www/openatlas/instance/
          docker cp testing.py openatlas:/var/www/openatlas/instance/
          docker exec -i openatlas /bin/bash -c "cd /var/www/openatlas/;python3 -m nose"
